name: Bug Report
description: File a bug report
title: '[Bug] '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! We'll try to help you as soon as possible so please provide as much information as you can.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what you see
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to happen?
      description: Tell us what you wanted to see
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce the issue
      description: Tell us how we can reproduce this issue. Please be specific and provide sample code if you can
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the library are you using?
      placeholder: ex. v1.0.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: What environment are you seeing the problem on?
      multiple: true
      options:
        - ReactJS (specify Browser below)
        - React Native (Android)
        - React Native (iOS)
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Microsoft Edge
        - Safari
        - Others

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Forward-Software/react-auth/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
