name: Feature Request
description: Suggest an idea for this project
title: '[Feature] '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this feature request! We'll try to help you as soon as possible so please provide as much information as you can.

  - type: textarea
    id: related-issue
    attributes:
      label: Is your feature request related to a problem?
      description: |
        A clear and concise description of what the problem is.
        E.g. I'm always frustrated when [...]

  - type: textarea
    id: feature-requested
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
