name: Coverage

on: [push, pull_request]

env:
  CI: true

jobs:
  coveralls:
    name: Code Coverage - Coveralls
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: node --version
      - run: npm --version

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: yarn test:coverage

      - name: Upload coverage results
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
