name: size

on: [pull_request]

jobs:
  size:
    runs-on: ubuntu-latest

    env:
      CI_JOB_NUMBER: 1

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Calculate output bundle sizes
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
